version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
    
    nginx:
        image: nginx:latest
        ports:
          - 8900:80
        volumes:
          - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - gateway
  
    gateway:
      image: localhost:5000/gateway:latest    
    accountservice:
      image:  localhost:5000/accountservice:latest
    api:
      image:  localhost:5000/api:latest
    gameservice:
      image:  localhost:5000/gameservice:latest
    photoservice:
      image:  localhost:5000/photoservice:latest